### ISSUE TITLE
It's raining in Belfast

### ISSUE THREAD

**Issue by kivikakk** [stevenwilkin/isitraininginbelfast.com#1]
But it says "no"!

I think Yahoo! may now be requiring some sort of authentication the `/forecastrss` endpoint? When I try curling it directly I get this:

> `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><yahoo:error xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xml:lang="en-US" yahoo:uri="http://yahoo.com"><yahoo:description>Please provide valid credentials. OAuth oauth_problem=&quot;OST_OAUTH_PARAMETER_ABSENT_ERROR&quot;, realm=&quot;yahooapis.com&quot;</yahoo:description><yahoo:detail>Please provide valid credentials. OAuth oauth_problem=&quot;OST_OAUTH_PARAMETER_ABSENT_ERROR&quot;, realm=&quot;yahooapis.com&quot;</yahoo:detail></yahoo:error>`

**Comment by stevenwilkin** [comment]
Yep, looks like an OAuth token is required to access that service now.
